version: '3'

services:
  django:
    image: django-docker:0.0.1
    restart: always
    build: .
    ports:
      - "8888:8888"
    depends_on:
      - migration
  migration:
    image: django-docker:0.0.1
    command: python manage.py migrate --noinput
    volumes:
      - .:/code