# Generated by Django 5.0.3 on 2024-03-25 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0004_alter_task_checked'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='checked',
            field=models.BooleanField(blank=True, default=False, null=True, verbose_name='checked'),
        ),
    ]
